### ISSUE TITLE
Use of the old Lyo Client drags the JSR311 dep

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.trs-client#28]
See https://github.com/eclipse/lyo.core/issues/79 for the bug report.

**Comment by berezovskyi** [comment]
Blocked by https://github.com/eclipse/lyo.client/issues/40

**Comment by berezovskyi** [comment]
Prompted by https://github.com/EricssonResearch/scott-eu/issues/150

**Comment by berezovskyi** [comment]
Absolute disaster is actually not a client API change but a use of the old OAuth classes & APIs throughout.

**Comment by jamsden** [comment]
I was aware of this. Is there a problem leaving this dependency in the old code?

**Comment by berezovskyi** [comment]
I am OK leaving it in the old adaptors but this one is about the TRS Client which I depend on in every new OSLC Server I build... So, no, this is not an option. But I managed to eliminate any OAuth-related code: it turned out to be a lot of exception signatures that dragged imports from oauth libs.
