### ISSUE TITLE
Rename to lyo-trs-client

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.trs-client#5]
I think Axel raised it some time ago etc.

In Lyo, we call a library for TRS Server a TRS Provider and a TRS Client application a TRS Consumer. It is clear for us but will confuse users. Before we release it in 2.4.0, do you want to rename the repository and the artefact name to `lyo-trs-client`?

**Comment by jadelkhoury** [comment]
yes

**Comment by berezovskyi** [comment]
See bug 531881

**Comment by berezovskyi** [comment]
Repo renamed, remaining:

- [ ] rename code references
- [ ] rename documentation references

**Comment by berezovskyi** [comment]
the renaming has been done in slightly different way, the tasks above are still relevant.

I suggest to change `org.eclipse.lyo.oslc4j.trs.consumer` to (let me experiment here with Github fancy features here and ask you to give 👍 to the option you like most or propose a new one):

@jadelkhoury @jamsden @yashkhatri

**Comment by berezovskyi** [comment]
First one: `org.eclipse.lyo.oslc4j.trs.client`

**Comment by berezovskyi** [comment]
Third one:

* `org.eclipse.lyo.trs.client` (package name)
* `org.eclipse.lyo.trs` (group name)
* `trs-client` artifact ID

**Comment by jamsden** [comment]
The TRS spec, similar to other OSLC specs, refers to clients and servers, and no longer uses the terms consumer or provider.

**Comment by berezovskyi** [comment]
@jamsden thanks, I am aware. Could you please indicate which of the options above would you prefer over the rest?

**Comment by jamsden** [comment]
2nd one.  Can the artifactId be trs.client instead of trs-client? Then the group name + artifactID = package name.

**Comment by jamsden** [comment]
Also eclipse project should correspond to artifactId not package name.

**Comment by berezovskyi** [comment]
thanks Jim, makes sense. regarding the eclipse project, I think there will not be any. Eclipse importer shall indeed use artifactId as basis.

**Comment by berezovskyi** [comment]
fixed in #10
